import pandas as pd
df = pd.read_csv('/Numpy /nyc_taxi.csv')
print(df)
print(df.shape)
print(df.head(2))
print(df.tail(1))
print(df.columns)
print(df['tip_amount '])
print(df[['pickup_month ','tip_amount ','fare_amount ']])
print(df['tip_amount '].max())
print(df.describe())
#print(df['pickup_month ', 'tip_amount '] [['tip_amount ']>=5])
print(df.index)
df.set_index('dropoff_location_code ', inplace=True)
print(df.head())
print(df.loc[4])
#print(df.columns)
